apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk 36

    defaultConfig {
        minSdkVersion 25
        targetSdkVersion 36
    }
    namespace 'com.stfalcon.imageviewer'

    kotlin {
        jvmToolchain(17)
    }
}

dependencies {
    api 'androidx.appcompat:appcompat:1.7.1'
    api 'androidx.transition:transition:1.6.0'
    implementation 'com.github.chrisbanes:PhotoView:2.2.0'
}

repositories {
    maven { url "https://jitpack.io" }
}

// Avoid Kotlin docs error
tasks.withType(Javadoc) {
    enabled = false
}

// Remove javadoc related tasks
task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}